-- Active: 1786667150004@@127.0.0.1@5432@bd_aula@public
CREATE TABLE curso{
    id_curso INTEGER  GENERATED ALWAYS AS IDENTIFY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL
}

CREATE TABLE aluno{
    id_auno INTEGER GENERATED ALWAYS AS IDENTIFY PRIMARY KEY,
    nome  VARCHAR(80) NOT NULL,
    id_curso INTEGER NOT NULL REFERENCES curso(id_curso)
}